import { useContext, useEffect, useRef, useState } from "react"
import { useEvent, useIsomorphicLayoutEffect, useScheduleLayoutEffect } from "@luminelabs/react-toolkit"
import type { DependencyContainer } from "../../aliases/index.js"

import type { ModuleResolution, ModuleResolutionParams } from "../../core/module/resolution.types.js"
import { ModuleContext, type ModuleContextValue } from "../context/ModuleContext.js"
import { createModuleResolution } from "../../core/module/resolution.js"

import type { ModuleHooks } from "../../core/providers/module-lifecycle/module-lifecycle.types.js"
import { ModuleLifecycle } from "../../core/providers/module-lifecycle/module-lifecycle.provider.js"

// useModule
// ========================================
export function useModule(params?: ModuleResolutionParams): ModuleContextValue {
    const parentContext = useContext(ModuleContext)
    const parentContainer = parentContext?.container ?? null
    const prevParentContainerRef = useRef(parentContainer)

    // React bridge for module hooks (latest closures, stable identities)
    const hooks = useModuleLifecycleHooks(params)

    // Resolution state. A rebuild swaps in a fresh resolution object; the effect keys on that object's
    // identity (the rebuild discriminator is object identity, not a counter). The public id lives on the
    // resolution, generated by createModuleResolution.
    const [resolution, setResolution] = useState<ModuleResolution>(() =>
        initializeModuleResolution(parentContainer, params, hooks)
    )

    // Lifecycle bridge — React supplies the commit/cleanup signal; the tree supplies the order.
    // setup   → resolve ModuleLifecycle → commit() (idempotent, cancels any pending teardown)
    // cleanup → resolve ModuleLifecycle → scheduleTeardown() (deferred microtask flush)
    useEffect(() => {
        commitModuleResolution(resolution)
        return () => scheduleModuleResolutionTeardown(resolution)
    }, [resolution])

    // Rebuilder. Uses scheduler to batch multiple rebuilds
    const schedule = useScheduleLayoutEffect()

    // Pure updater: builds the new resolution only. Teardown of the old resolution happens through the
    // effect path — the state swap runs the old effect's cleanup (scheduleTeardown), and the new effect
    // commits the new resolution.
    const performRebuild = useEvent(() => {
        setResolution(() => initializeModuleResolution(parentContainer, params, hooks))
    })

    const rebuild = useEvent(() => {
        schedule("module.rebuild", performRebuild)
    })

    // Scoped modules rebuild when the parent container changes.
    useEffect(() => {
        const isScopedMode = !params?.root && !params?.factory
        if (isScopedMode && prevParentContainerRef.current !== parentContainer) {
            rebuild()
        }

        prevParentContainerRef.current = parentContainer
    }, [parentContainer, rebuild])

    // rebuildOn: batched rebuild when any dependency changes (never on first render).
    const prevRebuildOnRef = useRef<unknown[] | undefined>(params?.rebuildOn)
    useIsomorphicLayoutEffect(() => {
        const prev = prevRebuildOnRef.current
        const next = params?.rebuildOn
        prevRebuildOnRef.current = next
        if (rebuildOnChanged(prev, next)) {
            rebuild()
        }
    })

    return {
        container: resolution.container,
        id: resolution.id,
        rebuild,
    }
}

function useModuleLifecycleHooks(params?: ModuleResolutionParams): ModuleHooks {
    const onModuleInitEvent = useEvent((container: DependencyContainer) => {
        params?.onModuleInit?.(container)
    })
    const onModuleMountEvent = useEvent((container: DependencyContainer) => {
        params?.onModuleMount?.(container)
    })
    const onModuleUnmountEvent = useEvent((container: DependencyContainer) => {
        params?.onModuleUnmount?.(container)
    })
    const onModuleDestroyEvent = useEvent((container: DependencyContainer) => {
        params?.onModuleDestroy?.(container)
    })
    return {
        onModuleInit: onModuleInitEvent,
        onModuleMount: onModuleMountEvent,
        onModuleUnmount: onModuleUnmountEvent,
        onModuleDestroy: onModuleDestroyEvent,
    }
}

// State processors
// ========================================
function initializeModuleResolution(
    parentContainer: DependencyContainer | null,
    params: ModuleResolutionParams | undefined,
    hooks: ModuleHooks
): ModuleResolution {
    const resolution = createModuleResolution(parentContainer, params)

    try {
        resolution.container.resolve(ModuleLifecycle).init(hooks)
    } catch (error) {
        try {
            const result = resolution.container.dispose()
            if (result instanceof Promise) {
                void result
            }
        } catch {
            // noop
        }
        throw error
    }

    return resolution
}

function rebuildOnChanged(prev: unknown[] | undefined, next: unknown[] | undefined): boolean {
    if (prev === undefined || next === undefined) return false
    if (prev.length !== next.length) return true
    for (let index = 0; index < prev.length; index++) {
        if (!Object.is(prev[index], next[index])) return true
    }
    return false
}

// Lifecycle processors
// ========================================
function commitModuleResolution(resolution: ModuleResolution): void {
    resolution.container.resolve(ModuleLifecycle).commit()
}

function scheduleModuleResolutionTeardown(resolution: ModuleResolution): void {
    resolution.container.resolve(ModuleLifecycle).scheduleTeardown()
}
